<?php

namespace Database\Seeders;

use App\Models\GtrModel;
use App\Models\User;
use Illuminate\Database\Seeder;

class GtrSeeder extends Seeder
{
    public function run(): void
    {
        // Create admin user
        User::create([
            'name' => 'Admin',
            'email' => 'admin@gtr-sport.com',
            'password' => bcrypt('password'),
            'is_admin' => true,
            'email_verified_at' => now(),
        ]);

        // Create demo user
        User::create([
            'name' => 'GT-R Fan',
            'email' => 'fan@gtr-sport.com',
            'password' => bcrypt('password'),
            'email_verified_at' => now(),
        ]);

        $models = [
            [
                'name' => 'Nissan Skyline GT-R R32',
                'slug' => 'nissan-skyline-gt-r-r32',
                'generation' => 'R32',
                'year_start' => 1989,
                'year_end' => 1994,
                'engine' => 'RB26DETT',
                'displacement' => '2.6L Twin-Turbo Inline-6',
                'horsepower' => 276,
                'torque' => '260 lb-ft (353 Nm)',
                'transmission' => '5-speed manual',
                'drivetrain' => 'ATTESA E-TS AWD',
                'acceleration' => '5.6 seconds (0-100 km/h)',
                'top_speed' => '243 km/h (151 mph)',
                'fuel_type' => 'Gasoline',
                'weight' => '1,430 kg (3,153 lbs)',
                'price' => '$45,000 - $150,000 (current market)',
                'description' => "The Nissan Skyline GT-R R32, introduced in 1989, earned the nickname \"Godzilla\" after completely dominating the Australian Touring Car Championship. Its legendary RB26DETT twin-turbo inline-six engine, combined with the innovative ATTESA E-TS all-wheel-drive system, redefined what a production sports car could achieve. The R32 was the first GT-R to feature the now-iconic RB26 engine, producing 276 hp in factory spec (though many believe actual output was higher due to Japan's gentleman\'s agreement). With a lightweight chassis, advanced suspension, and superb balance, the R32 became an instant legend in motorsport and street car culture.",
                'main_image' => 'https://s1.cdn.autoevolution.com/images/gallery/NISSAN-Skyline-GT-R--R32--4036_1.jpg',
                'is_nismo' => false,
                'is_featured' => true,
                'status' => 'active',
            ],
            [
                'name' => 'Nissan Skyline GT-R R33',
                'slug' => 'nissan-skyline-gt-r-r33',
                'generation' => 'R33',
                'year_start' => 1995,
                'year_end' => 1998,
                'engine' => 'RB26DETT',
                'displacement' => '2.6L Twin-Turbo Inline-6',
                'horsepower' => 276,
                'torque' => '260 lb-ft (353 Nm)',
                'transmission' => '5-speed manual',
                'drivetrain' => 'ATTESA E-TS AWD',
                'acceleration' => '5.0 seconds (0-100 km/h)',
                'top_speed' => '245 km/h (152 mph)',
                'fuel_type' => 'Gasoline',
                'weight' => '1,540 kg (3,395 lbs)',
                'price' => '$35,000 - $120,000 (current market)',
                'description' => "The R33 generation represented a significant evolution of the GT-R formula. Built on the slightly larger ENR33 platform, the R33 addressed the R32's structural rigidity shortcomings with a stiffer chassis and improved weight distribution. The RB26DETT received refinements including improved turbochargers and a more efficient intercooler system. The ATTESA E-TS system was upgraded with a multi-mode setting. Though initially criticized for its larger dimensions and weight gain, the R33 proved to be a faster, more refined GT-R. It set a Nürburgring lap record of 8:19 for a production sedan, cementing its performance credentials.",
                'main_image' => 'https://s1.cdn.autoevolution.com/images/gallery/NISSANSkylineGT-R-R33--4038_4.jpg',
                'is_nismo' => false,
                'is_featured' => false,
                'status' => 'active',
            ],
            [
                'name' => 'Nissan Skyline GT-R R33 LM',
                'slug' => 'nissan-skyline-gt-r-r33-lm',
                'generation' => 'R33',
                'year_start' => 1995,
                'year_end' => 1995,
                'engine' => 'RB26DETT',
                'displacement' => '2.6L Twin-Turbo Inline-6',
                'horsepower' => 276,
                'torque' => '260 lb-ft (353 Nm)',
                'transmission' => '5-speed manual',
                'drivetrain' => 'ATTESA E-TS AWD',
                'acceleration' => '5.0 seconds (0-100 km/h)',
                'top_speed' => '245 km/h (152 mph)',
                'fuel_type' => 'Gasoline',
                'weight' => '1,540 kg (3,395 lbs)',
                'price' => '$60,000 - $180,000 (current market)',
                'description' => "The R33 GT-R LM was a limited production homologation special built to celebrate Nissan's return to the 24 Hours of Le Mans in 1995. Only 5 units were produced for the road. The LM featured a unique Midnight Purple paint color, distinctive LMG-tuned suspension, and subtle aerodynamic improvements. Based on the GTS-25t, it featured the full GT-R drivetrain with the RB26DETT and ATTESA E-TS. The LM remains one of the rarest and most sought-after GT-R variants in existence.",
                'main_image' => 'https://s1.cdn.autoevolution.com/images/gallery/NISSAN-Skyline-GT-R--R33--4038_7.jpg',
                'is_nismo' => false,
                'is_featured' => false,
                'status' => 'active',
            ],
            [
                'name' => 'Nissan Skyline GT-R R34',
                'slug' => 'nissan-skyline-gt-r-r34',
                'generation' => 'R34',
                'year_start' => 1999,
                'year_end' => 2002,
                'engine' => 'RB26DETT',
                'displacement' => '2.6L Twin-Turbo Inline-6',
                'horsepower' => 276,
                'torque' => '260 lb-ft (353 Nm)',
                'transmission' => '6-speed manual',
                'drivetrain' => 'ATTESA E-TS with GT-R mode AWD',
                'acceleration' => '4.9 seconds (0-100 km/h)',
                'top_speed' => '250 km/h (155 mph)',
                'fuel_type' => 'Gasoline',
                'weight' => '1,540 kg (3,395 lbs)',
                'price' => '$100,000 - $350,000+ (current market)',
                'description' => "The R34 Skyline GT-R is widely regarded as the ultimate expression of the Skyline GT-R lineage. Introduced in 1999, it featured a shorter wheelbase than the R33, providing sharper handling. The interior showcased a revolutionary Multi-Function Display (MFD) showing real-time vehicle data — a first in production cars. The RB26DETT received further refinements, and the ATTESA E-TS system gained a dedicated GT-R mode for more rear-biased power distribution. The 6-speed close-ratio Getrag transmission provided precise gear changes. The R34's combination of technology, performance, and iconic styling made it an instant collector's item, with values skyrocketing in the years since production ended.",
                'main_image' => 'https://s1.cdn.autoevolution.com/images/news/gallery/nissan-rb26dett-the-skyline-gt-rs-legendary-turbocharged-inline-six_13.jpg',
                'is_nismo' => false,
                'is_featured' => true,
                'status' => 'active',
            ],
            [
                'name' => 'Nissan Skyline GT-R R34 V-Spec',
                'slug' => 'nissan-skyline-gt-r-r34-v-spec',
                'generation' => 'R34',
                'year_start' => 1999,
                'year_end' => 2002,
                'engine' => 'RB26DETT',
                'displacement' => '2.6L Twin-Turbo Inline-6',
                'horsepower' => 276,
                'torque' => '260 lb-ft (353 Nm)',
                'transmission' => '6-speed manual',
                'drivetrain' => 'ATTESA E-TS with GT-R mode AWD',
                'acceleration' => '4.8 seconds (0-100 km/h)',
                'top_speed' => '250 km/h (155 mph)',
                'fuel_type' => 'Gasoline',
                'weight' => '1,520 kg (3,351 lbs)',
                'price' => '$150,000 - $500,000+ (current market)',
                'description' => "The V-Spec (Victory Specification) represented the pinnacle of the R34 GT-R range. Building on the standard R34, the V-Spec added ATTESA E-TS Pro with active rear-steer capability, a carbon fiber rear diffuser, firmer suspension, and Bilstein dampers. The interior featured Alcantara trim and unique instrumentation. The V-Spec II, introduced in 2001, further enhanced the formula with additional carbon fiber components and weight reduction measures. The V-Spec models are the most collectible of all R34 variants, commanding premium prices at auction.",
                'main_image' => 'https://s1.cdn.autoevolution.com/images/news/gallery/nissan-rb26dett-the-skyline-gt-rs-legendary-turbocharged-inline-six_14.jpg',
                'is_nismo' => false,
                'is_featured' => false,
                'status' => 'active',
            ],
            [
                'name' => 'Nissan Skyline GT-R R34 Nür',
                'slug' => 'nissan-skyline-gt-r-r34-nur',
                'generation' => 'R34',
                'year_start' => 2002,
                'year_end' => 2002,
                'engine' => 'RB26DETT N1',
                'displacement' => '2.6L Twin-Turbo Inline-6',
                'horsepower' => 276,
                'torque' => '260 lb-ft (353 Nm)',
                'transmission' => '6-speed manual',
                'drivetrain' => 'ATTESA E-TS with GT-R mode AWD',
                'acceleration' => '4.7 seconds (0-100 km/h)',
                'top_speed' => '250 km/h (155 mph)',
                'fuel_type' => 'Gasoline',
                'weight' => '1,510 kg (3,329 lbs)',
                'price' => '$300,000 - $800,000+ (current market)',
                'description' => "The R34 GT-R Nür (officially V-Spec II Nür) is the ultimate and final Skyline GT-R. Named after the Nürburgring where the GT-R earned its racing reputation, only 718 units were produced (497 V-Spec II Nür and 221 M-Spec Nür). It featured the N1-spec RB26DETT engine with larger turbochargers and reinforced internals, a carbon fiber hood, and unique Millennium Jade or Mystic Lust paint colors. The Nür is the rarest and most valuable production GT-R ever made, representing the end of the RB26 era.",
                'main_image' => 'https://s1.cdn.autoevolution.com/images/news/gallery/the-r34-nissan-skyline-gt-r-what-s-the-deal_5.jpg',
                'is_nismo' => false,
                'is_featured' => false,
                'status' => 'active',
            ],
            [
                'name' => 'Nissan GT-R R35',
                'slug' => 'nissan-gt-r-r35',
                'generation' => 'R35',
                'year_start' => 2007,
                'year_end' => 2025,
                'engine' => 'VR38DETT',
                'displacement' => '3.8L Twin-Turbo V6',
                'horsepower' => 480,
                'torque' => '430 lb-ft (583 Nm)',
                'transmission' => '6-speed dual-clutch (GR6)',
                'drivetrain' => 'ATTESA E-TS AWD',
                'acceleration' => '3.5 seconds (0-100 km/h)',
                'top_speed' => '315 km/h (196 mph)',
                'fuel_type' => 'Gasoline',
                'weight' => '1,740 kg (3,836 lbs)',
                'price' => '$113,540 (MSRP 2009)',
                'description' => "The R35 GT-R marked a radical departure from the Skyline lineage, emerging as a standalone model. Launched at the 2007 Tokyo Motor Show, it was designed to challenge the world's best supercars at a fraction of the price. The hand-built VR38DETT 3.8-liter twin-turbo V6, mated to a rear-mounted 6-speed dual-clutch transmission, delivered explosive acceleration. The advanced ATTESA E-TS system used a rear-mounted transaxle with a torque tube for optimal weight distribution. Its aerodynamic body achieved a drag coefficient of just 0.27. The R35 quickly earned the nickname \"Godzilla\" reborn, capable of outperforming vehicles costing three times its price.",
                'main_image' => 'https://s1.cdn.autoevolution.com/images/gallery/NISSANGT-R-3701_1.jpg',
                'is_nismo' => false,
                'is_featured' => true,
                'status' => 'active',
            ],
            [
                'name' => 'Nissan GT-R R35 Premium',
                'slug' => 'nissan-gt-r-r35-premium',
                'generation' => 'R35',
                'year_start' => 2009,
                'year_end' => 2025,
                'engine' => 'VR38DETT',
                'displacement' => '3.8L Twin-Turbo V6',
                'horsepower' => 565,
                'torque' => '467 lb-ft (633 Nm)',
                'transmission' => '6-speed dual-clutch (GR6)',
                'drivetrain' => 'ATTESA E-TS AWD',
                'acceleration' => '3.0 seconds (0-100 km/h)',
                'top_speed' => '315 km/h (196 mph)',
                'fuel_type' => 'Gasoline',
                'weight' => '1,740 kg (3,836 lbs)',
                'price' => '$113,540 (MSRP)',
                'description' => "The GT-R Premium is the definitive R35 experience, balancing performance with luxury. Equipped with the VR38DETT producing 565 hp (later models), the Premium features leather-appointed interior, Bose audio system, heated/ventilated front seats, and the latest in connectivity technology. The Premium trim includes the standard ATTESA E-TS AWD, Brembo brakes, Bilstein DampTronic suspension, and 20-inch forged aluminum wheels. It remains one of the best performance values in the automotive world, rivaling supercars costing multiples of its price.",
                'main_image' => 'https://s1.cdn.autoevolution.com/images/gallery/NISSANGT-R-R35--Facelift-4438_1.jpg',
                'is_nismo' => false,
                'is_featured' => false,
                'status' => 'active',
            ],
            [
                'name' => 'Nissan GT-R R35 T-spec',
                'slug' => 'nissan-gt-r-r35-t-spec',
                'generation' => 'R35',
                'year_start' => 2021,
                'year_end' => 2025,
                'engine' => 'VR38DETT',
                'displacement' => '3.8L Twin-Turbo V6',
                'horsepower' => 565,
                'torque' => '467 lb-ft (633 Nm)',
                'transmission' => '6-speed dual-clutch (GR6)',
                'drivetrain' => 'ATTESA E-TS AWD',
                'acceleration' => '2.9 seconds (0-100 km/h)',
                'top_speed' => '315 km/h (196 mph)',
                'fuel_type' => 'Gasoline',
                'weight' => '1,725 kg (3,803 lbs)',
                'price' => '$141,040 (MSRP)',
                'description' => "The GT-R T-spec bridges the gap between the Premium and NISMO, offering a focused driving experience without the extreme edge of the full NISMO. It features a lightweight carbon fiber roof, wider front fenders borrowed from the NISMO, a unique Mori Green paint option, and specially tuned Bilstein DampTronic dampers. The interior receives exclusive interior trim and Nismo-spec seats. The T-spec includes carbon ceramic brakes as standard, providing incredible stopping power with reduced unsprung weight. It represents the most balanced expression of the R35 GT-R's dual nature.",
                'main_image' => 'https://s1.cdn.autoevolution.com/images/gallery/NISSANGT-R-R35--Facelift-4438_2.jpg',
                'is_nismo' => false,
                'is_featured' => false,
                'status' => 'active',
            ],
            [
                'name' => 'Nissan GT-R NISMO',
                'slug' => 'nissan-gt-r-nismo',
                'generation' => 'R35',
                'year_start' => 2014,
                'year_end' => 2024,
                'engine' => 'VR38DETT NISMO',
                'displacement' => '3.8L Twin-Turbo V6',
                'horsepower' => 600,
                'torque' => '481 lb-ft (652 Nm)',
                'transmission' => '6-speed dual-clutch (GR6)',
                'drivetrain' => 'ATTESA E-TS AWD',
                'acceleration' => '2.5 seconds (0-100 km/h)',
                'top_speed' => '315 km/h (196 mph)',
                'fuel_type' => 'Gasoline',
                'weight' => '1,725 kg (3,803 lbs)',
                'price' => '$210,740 (MSRP)',
                'description' => "The GT-R NISMO is the ultimate production GT-R, developed by Nissan's motorsport division NISMO (Nissan Motorsport International). It features hand-tuned VR38DETT engines producing 600 hp, a more aggressive body with enhanced aerodynamics generating significant downforce, a lightweight carbon fiber hood, roof, and spoiler, and race-derived suspension components. The NISMO includes wider tires, recalibrated ATTESA E-TS, and a rear-mounted transmission for improved weight distribution. It holds a Nürburgring Nordschleife lap record of 7:08.679 for a production car, making it one of the fastest four-door production cars in history.",
                'main_image' => 'https://s1.cdn.autoevolution.com/images/gallery/NISSAN-GT-R--R35--Nismo-5327_25.jpg',
                'is_nismo' => true,
                'is_featured' => true,
                'status' => 'active',
            ],
            [
                'name' => 'Nissan GT-R NISMO Special Edition',
                'slug' => 'nissan-gt-r-nismo-special-edition',
                'generation' => 'R35',
                'year_start' => 2022,
                'year_end' => 2024,
                'engine' => 'VR38DETT NISMO',
                'displacement' => '3.8L Twin-Turbo V6',
                'horsepower' => 600,
                'torque' => '481 lb-ft (652 Nm)',
                'transmission' => '6-speed dual-clutch (GR6)',
                'drivetrain' => 'ATTESA E-TS AWD',
                'acceleration' => '2.4 seconds (0-100 km/h)',
                'top_speed' => '315 km/h (196 mph)',
                'fuel_type' => 'Gasoline',
                'weight' => '1,715 kg (3,781 lbs)',
                'price' => '$221,040 (MSRP)',
                "description" => "The GT-R NISMO Special Edition is the most extreme and limited variant of the R35 GT-R ever produced. Limited to just 300 units globally, it features exclusive Stealth Gray paintwork, carbon fiber body components with exposed weave, and uniquely serialized interior plaques. Each engine is hand-assembled by a single Takumi master craftsman and signed with a nameplate. The Special Edition benefits from further weight reduction, recalibrated suspension, and exclusive 20-inch Rays forged alloy wheels with Dunlop GT600 tires. The interior features carbon fiber bucket seats with red Alcantara accents and unique instrumentation.",
                'main_image' => 'https://s1.cdn.autoevolution.com/images/news/gallery/2022-nissan-gt-r-sold-out-water-still-wet_1.jpg',
                'is_nismo' => true,
                'is_featured' => false,
                'status' => 'active',
            ],
        ];

        foreach ($models as $modelData) {
            GtrModel::create($modelData);
        }
    }
}
